#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_platform:
    resource: .
    type: api_platform
    prefix: /api
authentication_token:
    path: /authentication_token
    methods: ['POST']